# Demonstrate use of tensorflow and pytorch by implementing simple code in python

TENSORFLOW

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
a=tf.constant(10)
b=tf.constant(20)
print(a+b)

tf.Tensor(30, shape=(), dtype=int32)


In [4]:
x=np.random.rand(100).astype(np.float32)
print(x)

[0.6795683  0.35367537 0.74718565 0.39987734 0.35852882 0.7180365
 0.7384104  0.99369097 0.5140861  0.63944334 0.20234004 0.4964164
 0.73423856 0.04778801 0.278043   0.7841469  0.7189814  0.56587774
 0.48560596 0.68812615 0.94860387 0.85947394 0.73190594 0.74596083
 0.4108094  0.7652801  0.50047755 0.25128016 0.58734334 0.856778
 0.5582943  0.2959523  0.4582861  0.5223039  0.3900183  0.2782173
 0.51970303 0.33896312 0.6950003  0.9927198  0.16624202 0.9838171
 0.202631   0.03597032 0.19565375 0.13547747 0.90387416 0.17810419
 0.5800428  0.8040571  0.34058574 0.04183109 0.3512217  0.02976646
 0.79229766 0.45319593 0.03713045 0.6884081  0.7631279  0.942325
 0.60228217 0.10273151 0.81266004 0.44425556 0.68150604 0.32759124
 0.17723614 0.32396504 0.7437358  0.686741   0.9848305  0.06010335
 0.69618744 0.9836456  0.0949913  0.44982433 0.96096635 0.3108573
 0.1366826  0.07360211 0.63300186 0.47699305 0.73116684 0.51964927
 0.18348475 0.5788622  0.97796583 0.31484142 0.08738756 0.32491165
 0.4

In [5]:
y=x*0.2+0.2

In [6]:
#weight initialization
w=tf.Variable(tf.random.normal([1]))

In [7]:
#assigning bias value
b=tf.Variable(tf.zeros([1]))

In [8]:
#creating mean squared error function
def mse_loss():
    y_pred=w*x+b
    loss=tf.reduce_mean(tf.square(y_pred-y))
    return loss

In [9]:
#optimizer
opt=tf.keras.optimizers.Adam()

In [10]:
#iterations
for i in range(5000):
    opt.minimize(mse_loss,var_list=[w,b])
    if i%500==0:
        print(i, w.numpy(), b.numpy())

0 [0.73290837] [-0.00099998]
500 [0.40495983] [0.09131231]
1000 [0.24206525] [0.17772128]
1500 [0.20394549] [0.19791049]
2000 [0.20014074] [0.19992547]
2500 [0.20000161] [0.19999917]
3000 [0.20000061] [0.19999968]
3500 [0.20000046] [0.19999975]
4000 [0.20000036] [0.19999981]
4500 [0.20000026] [0.19999987]


PYTORCH

In [11]:
pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [12]:
import torch
import numpy as np

In [13]:
#tenor initialization using data
data=[
    [1,2],
    [3,4]
]
x_data=torch.tensor(data)

In [14]:
print(x_data)
print(type(x_data))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [15]:
#tensor initialization using numpy array
np_array=np.array(data)
x_np=torch.from_numpy(np_array)
print(x_np)
print(type(x_np))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [16]:
#tensor initialization using another tensor
x_ones=torch.ones_like(x_data)
print("One Tensor : \n ",x_ones)
x_rand=torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

One Tensor : 
  tensor([[1, 1],
        [1, 1]])
tensor([[0.9520, 0.9769],
        [0.2943, 0.3897]])


In [17]:
#other ways of tensor creation and initialization
shape=(2,3)
random_tensor=torch.rand(shape)
print(random_tensor)
print(type(random_tensor))

tensor([[0.3959, 0.0997, 0.7572],
        [0.4975, 0.6008, 0.0593]])
<class 'torch.Tensor'>


In [18]:
#Tensor operations
#indexing and slicing
tensor=torch.ones(4,4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [19]:
tensor1 = torch.zeros(4,4)
print(tensor1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [20]:
tensor2 = torch.cat([tensor,tensor1])
print(tensor2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [21]:
#multiplication operation
tensor.mul(tensor1)
tensor * tensor1
tensor.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
#addition operation
tensor.add_(3)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [23]:
# from tensor to numpy
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(type(n))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
